name = "Modsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bc8e8e4ef350906ac9c123db0a62060b2c559b885f1a80d17bb8cd4d3744c5b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
